# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: Grade for submission
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Install project-utils
      working-directory: ./project-utils
      run: mvn -ntp install

    - name: Verify
      run: mvn -ntp verify

    - name: Checkstyle check
      run: mvn -ntp checkstyle:check -Dcheckstyle.violationSeverity=warning

    - name: Output type proofs
      if: always()
      run: mvn -ntp exec:java 
      continue-on-error: true

    - name: Report mutation coverage
      if: always()
      run: |
        mvn -ntp -DoutputFormats=CSV test org.pitest:pitest-maven:mutationCoverage
        echo "Mutations not killed:"
        echo "File                      Line  Status       Mutator"
        awk -F, ' $6 != "KILLED" { printf "%-25s %-5s %-12s %-40s\n", $1, $5, $6, substr($3, 48);}' target/pit-reports/*/mutations.csv; 
